plugins {
    id 'idea'
    id 'java-library'
    id 'maven-publish'
    id 'net.neoforged.moddev' version '2.0.73'
}

tasks.named('wrapper', Wrapper).configure {
    // Define wrapper values here so as to not have to always do so when updating gradlew.properties.
    // Switching this to Wrapper.DistributionType.ALL will download the full gradle sources that comes with
    // documentation attached on cursor hover of gradle classes and methods. However, this comes with increased
    // file size for Gradle. If you do switch this to ALL, run the Gradle wrapper task twice afterwards.
    // (Verify by checking gradle/wrapper/gradle-wrapper.properties to see if distributionUrl now points to `-all`)
    distributionType = Wrapper.DistributionType.BIN
}

version = mod_version
group = maven_group

repositories {
    mavenLocal()
    maven {
        url 'https://maven.terraformersmc.com/releases/'
        content {
            includeGroup 'dev.emi'
        }
    }
    maven {
        url 'https://api.modrinth.com/maven/'
        content {
            includeGroup 'maven.modrinth'
        }
    }
    maven {
        url 'https://cursemaven.com'
        content {
            includeGroup 'curse.maven'
        }
    }
}

base {
    archivesName = mod_id
}

// Mojang ships Java 21 to end users starting in 1.20.5, so mods should target Java 21.
java.toolchain.languageVersion = JavaLanguageVersion.of(21)

neoForge {
    version = project.neo_version

    runs {
        client {
            client()
        }
        server {
            server()
        }
        data {
            data()
        }
    }

    mods {
        "${mod_id}" {
            sourceSet(sourceSets.main)
        }
    }
}

// Include resources generated by data generators.
sourceSets.main.resources { srcDir 'src/generated/resources' }

// Sets up a dependency configuration called 'localRuntime'.
// This configuration should be used instead of 'runtimeOnly' to declare
// a dependency that will be present for runtime testing but that is
// "optional", meaning it will not be pulled by dependents of this mod.
configurations {
    runtimeClasspath.extendsFrom localRuntime
}

dependencies {
    dependencies.ext.mod = { String dep ->
        implementation(dep) {
            exclude group: "me.shedaniel"
            exclude group: "mezz.jei"
        }
    }

    compileOnly "dev.emi:emi-neoforge:${emi_version}:api"
    runtimeOnly "dev.emi:emi-neoforge:${emi_version}"

    dependencies.ext.mod "maven.modrinth:chipped:${chipped_version}"
    dependencies.ext.mod "maven.modrinth:rechiseled:${rechiseled_version}"
    dependencies.ext.mod "maven.modrinth:reliquary-reincarnations:${reliquary_version}"
    dependencies.ext.mod "maven.modrinth:irons-spells-n-spellbooks:${isns_version}"
//    dependencies.ext.mod "curse.maven:apotheosis-313970:${apotheosis_version}"
    dependencies.ext.mod "maven.modrinth:pneumaticcraft-repressurized:${pnc_version}"
    dependencies.ext.mod "curse.maven:ars-nouveau-401955:${ars_version}"
    dependencies.ext.mod "maven.modrinth:farmers-delight:${fd_version}"
    dependencies.ext.mod "curse.maven:ftb-quests-forge-289412:${ftbq_version}"
    dependencies.ext.mod "maven.modrinth:actually-additions:nO8yMIM0"

    // mod dependencies
    localRuntime "maven.modrinth:curios-continuation:WnSvqCaY"
    localRuntime "maven.modrinth:geckolib:oNBe6h9g"
    localRuntime "maven.modrinth:resourceful-lib:XjYVlVPE"
    localRuntime "maven.modrinth:playeranimator:q60QWuOK"
    localRuntime "maven.modrinth:athena-ctm:zzovqkDA"
    localRuntime "maven.modrinth:supermartijn642s-config-lib:qKL9jM75"
    localRuntime "maven.modrinth:supermartijn642s-core-lib:i7nRl7jh"
    localRuntime "curse.maven:placebo-283644:6050938"
    localRuntime "curse.maven:ftb-library-forge-404465:6016745"
    localRuntime "curse.maven:ftb-teams-forge-404468:5882217"
    localRuntime "maven.modrinth:architectury-api:ZxYGwlk0"
    localRuntime "maven.modrinth:fusion-connected-textures:Z8Hlv22C"
}

// This block of code expands all declared replace properties in the specified resource targets.
// A missing property will result in an error. Properties are expanded using ${} Groovy notation.
var generateModMetadata = tasks.register("generateModMetadata", ProcessResources) {
    var replaceProperties = [
            minecraft_version      : minecraft_version,
            minecraft_version_range: minecraft_version_range,
            neo_version            : neo_version,
            neo_version_range      : neo_version_range,
            loader_version_range   : loader_version_range,
            mod_id                 : mod_id,
            mod_name               : mod_name,
            mod_license            : mod_license,
            mod_version            : mod_version,
            mod_authors            : mod_authors,
            mod_description        : mod_description
    ]
    inputs.properties replaceProperties
    expand replaceProperties
    from "src/main/templates"
    into "build/generated/sources/modMetadata"
}
// Include the output of "generateModMetadata" as an input directory for the build
// this works with both building through Gradle and the IDE.
sourceSets.main.resources.srcDir generateModMetadata
// To avoid having to run "generateModMetadata" manually, make it run on every project reload
neoForge.ideSyncTask generateModMetadata

// Example configuration to allow publishing using the maven-publish plugin
publishing {
    publications {
        register('mavenJava', MavenPublication) {
            from components.java
        }
    }
    repositories {
        maven {
            url "file://${project.projectDir}/repo"
        }
    }
}

tasks.withType(JavaCompile).configureEach {
    options.encoding = 'UTF-8' // Use the UTF-8 charset for Java compilation
}

// IDEA no longer automatically downloads sources/javadoc jars for dependencies, so we need to explicitly enable the behavior.
idea {
    module {
        downloadSources = true
        downloadJavadoc = true
    }
}